default: &default
  adapter: mysql2
  user: root
  password: rata
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: simple_subdomain-development

test:
  <<: *default
  database: simple_subdomain-test

production:
  <<: *default
  database: simple_subdomain-production
